### ISSUE TITLE
Add expansion pak support for the n64

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [LitRitt/Ignited#26]
Some n64 games run better with the expansion pak, and I think the emulator is using a fake expansion pak. Some games think they have an expansion pak installed when there actually isn’t. For example, in donkey Kong 64, when you start a game, there’s no zipper effect like using a real n64 and pak. Banjo-kazooie has fading in and out puzzle pieces which don’t have textures of the current screen. And last but not least, conker’s bad fur day is a bloody mess, missing textures, bad model overlays, and other things I haven’t seen yet.
![Banjo-Kazooie (USA)_2023-06-15_18-42-33](https://github.com/Lit-Development/Ignited/assets/79031143/6ff5c94c-0b67-4a18-aec6-86cbc1f2e752)
![Conker's Bad Fur Day (USA)_2023-06-15_18-44-03](https://github.com/Lit-Development/Ignited/assets/79031143/3fff819d-c361-4d6f-a19b-8df27693530f)
![Conker's Bad Fur Day (USA)_2023-06-15_18-44-05](https://github.com/Lit-Development/Ignited/assets/79031143/db0e85b8-8a56-4aa6-996d-45fae7cae9ee)
![Donkey Kong 64 (USA)_2023-06-15_18-43-31](https://github.com/Lit-Development/Ignited/assets/79031143/325788ce-78d0-4749-b05b-bfc6d469488a)

**Comment by LitRitt** [comment]
I don't think the emulator core has any kind of fake expansion pak? That would be kind of stupid. The n64 core is just very outdated and needs updated.
